

export const SELECT_CURRENCY_POP_UP = "SELECT_CURRENCY_POP_UP"
export const SELECT_CATEGORY_POP_UP = "SELECT_CATEGORY_POP_UP"
export const SELECT_SERVICE_POP_UP = "SELECT_SERVICE_POP_UP"
export const SELECT_PAYMENT_METHOD_POP_UP = "SELECT_PAYMENT_METHOD_POP_UP"

