

export const SELECT_CURRENCY_POP_UP = "SELECT_CURRENCY_POP_UP"
export const SELECT_CATEGORY_POP_UP = "SELECT_CATEGORY_POP_UP"
export const SELECT_SERVICE_POP_UP = "SELECT_SERVICE_POP_UP"
export const SELECT_PAYMENT_METHOD_POP_UP = "SELECT_PAYMENT_METHOD_POP_UP"
export const SELECT_AMOUNT_OF_MONEY_POP_UP = "SELECT_AMOUNT_OF_MONEY_POP_UP"



export const ADMIN_PANEL_EDIT_USER = "ADMIN_PANEL_EDIT_USER"




export const ADMIN_PANEL_CREATE_FAQS = "ADMIN_PANEL_CREATE_FAQS"
export const ADMIN_PANEL_EDIT_FAQS = "ADMIN_PANEL_EDIT_FAQS"




export const ADMIN_PANEL_CREATE_BLOG = "ADMIN_PANEL_CREATE_BLOG"
export const ADMIN_PANEL_EDIT_BLOG = "ADMIN_PANEL_EDIT_BLOG"



export const ADMIN_PANEL_CREATE_PLATFORM = "ADMIN_PANEL_CREATE_PLATFORM"


export const ADMIN_PANEL_CREATE_PAYMENT_METHOD = "ADMIN_PANEL_CREATE_PLATFORM"
